name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mi-app-web-CL'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_874541BD_B123_4A2D_9C1A_3D8839066601 }} # Conserva el nombre exacto de tu secret original
          package: .
